pacman:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: shuguet
    image: pacman
    tag: latest
    pullPolicy: Always

mongodb:
  enabled: true

## Service configuration.
service:
  type: ClusterIP
  port: 80

## Ingress configuration.
ingress:
  create: false
